const ai3x3 = {
  database: {
    firstMoveScenario1:{
      playerMove:1,
      aiMove:5,
      secondMoveScenario1:{
        playerMove:2,
        aiMove:3,
        thirdMoveScenario1:{
          playerMove:4,
          aiMove:7
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:7
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:7
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:4,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:8
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:6
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:6
          }
        },
        thirdMoveScenario5:{
          playerMove:3,
          aiMove:7
        }
      },
      secondMoveScenario2:{
        playerMove:3,
        aiMove:2,
        thirdMoveScenario1:{
          playerMove:6,
          aiMove:8
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:8
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:4,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:9
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:6
          },
          fourthMoveScenario3:{
            playerMove:7,
            aiMove:6
          }
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:8
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:8
        }
      },
      secondMoveScenario3:{
        playerMove:6,
        aiMove:8,
        thirdMoveScenario1:{
          playerMove:2,
          aiMove:3,
          fourthMoveScenario1:{
            playerMove:9,
            aiMove:7
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:4
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:7
          }
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:2
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:2
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:2
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:2
        }
      },
      secondMoveScenario4:{
        playerMove:9,
        aiMove:2,
        thirdMoveScenario1:{
          playerMove:3,
          aiMove:8
        },
        thirdMoveScenario2:{
          playerMove:6,
          aiMove:8
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:7,
          fourthMoveScenario1:{
            playerMove:3,
            aiMove:6
          },
          fourthMoveScenario2:{
            playerMove:6,
            aiMove:3
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:3
          }
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:8
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:8
        }
      },
      secondMoveScenario5:{
        playerMove:8,
        aiMove:6,
        thirdMoveScenario1:{
          playerMove:2,
          aiMove:4
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:4
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:4
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:4
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:7,
          fourthMoveScenario1:{
            playerMove:2,
            aiMove:3
          },
          fourthMoveScenario2:{
            playerMove:3,
            aiMove:2
          },
          fourthMoveScenario3:{
            playerMove:9,
            aiMove:3
          }
        }
      },
      secondMoveScenario6:{
        playerMove:7,
        aiMove:4,
        thirdMoveScenario1:{
          playerMove:2,
          aiMove:6
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:6
        },
        thirdMoveScenario3:{
          playerMove:6,
          aiMove:4,
          fourthMoveScenario1:{
            playerMove:3,
            aiMove:8
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:9
          }
        },
        thirdMoveScenario4:{
          playerMove:9,
          aiMove:6
        },
        thirdMoveScenario5:{
          playerMove:8,
          aiMove:6,
        }
      },
      secondMoveScenario7:{
        playerMove:4,
        aiMove:7,
        thirdMoveScenario1:{
          playerMove:2,
          aiMove:3
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:2,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:8
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:6
          }
        },
        thirdMoveScenario3:{
          playerMove:6,
          aiMove:3
        },
        thirdMoveScenario4:{
          playerMove:9,
          aiMove:3
        },
        thirdMoveScenario5:{
          playerMove:8,
          aiMove:3
        }
      }
    },
    firstMoveScenario2:{
      playerMove:2,
      aiMove:5,
      secondMoveScenario1:{
        playerMove:1,
        aiMove:3,
        thirdMoveScenario1:{
          playerMove:6,
          aiMove:7
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:7
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:7
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:4,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:8
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:6
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:6
          }
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:7
        }
      },
      secondMoveScenario2:{
        playerMove:3,
        aiMove:1,
        thirdMoveScenario1:{
          playerMove:6,
          aiMove:9
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:6,
          fourthMoveScenario1:{
            playerMove:8,
            aiMove:4
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:4
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:7
          }
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:9
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:9
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:9
        }
      },
      secondMoveScenario3:{
        playerMove:6,
        aiMove:1,
        thirdMoveScenario1:{
          playerMove:3,
          aiMove:9
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:3,
          fourthMoveScenario1:{
            playerMove:8,
            aiMove:7
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:7
          }
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:9
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:9
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:9
        }
      },
      secondMoveScenario4:{
        playerMove:9,
        aiMove:4,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:6
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:6
        },
        thirdMoveScenario3:{
          playerMove:6,
          aiMove:3,
          fourthMoveScenario1:{
            playerMove:1,
            aiMove:7
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:7
          }
        },
        thirdMoveScenario4:{
          playerMove:8,
          aiMove:6
        },
        thirdMoveScenario5:{
          playerMove:7,
          aiMove:6
        }
      },
      secondMoveScenario5:{
        playerMove:8,
        aiMove:1,
        thirdMoveScenario1:{
          playerMove:3,
          aiMove:9
        },
        thirdMoveScenario2:{
          playerMove:6,
          aiMove:9
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:7,
          fourthMoveScenario1:{
            playerMove:3,
            aiMove:4
          },
          fourthMoveScenario2:{
            playerMove:6,
            aiMove:3
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:3
          }
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:9
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:9
        }
      },
      secondMoveScenario6:{
        playerMove:7,
        aiMove:6,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:4
        },
        thirdMoveScenario2:{
          playerMove:3,
          aiMove:4
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:4
        },
        thirdMoveScenario4:{
          playerMove:8,
          aiMove:4
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:1,
          fourthMoveScenario1:{
            playerMove:3,
            aiMove:9
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:9
          }
        }
      },
      secondMoveScenario7:{
        playerMove:4,
        aiMove:3,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:7
        },
        thirdMoveScenario2:{
          playerMove:6,
          aiMove:7
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:7
        },
        thirdMoveScenario4:{
          playerMove:8,
          aiMove:7
        },
        thirdMoveScenario5:{
          playerMove:7,
          aiMove:1,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:9
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:8,
            aiMove:9
          }
        }
      }
    },
    firstMoveScenario3:{
      playerMove:3,
      aiMove:5,
      secondMoveScenario1:{
        playerMove:3,
        aiMove:2,
        thirdMoveScenario1:{
          playerMove:6,
          aiMove:8
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:8
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:4,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:9
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:6
          },
          fourthMoveScenario3:{
            playerMove:7,
            aiMove:6
          }
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:8
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:8
        }
      },
      secondMoveScenario2:{
        playerMove:2,
        aiMove:1,
        thirdMoveScenario1:{
          playerMove:6,
          aiMove:9
        },
        thirdMoveScenario2:{
          playerMove:9,
          aiMove:6,
          fourthMoveScenario1:{
            playerMove:8,
            aiMove:4
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:4
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:7
          }
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:9
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:9
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:9
        }
      },
      secondMoveScenario3:{
        playerMove:6,
        aiMove:9,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:2,
          fourthMoveScenario1:{
            playerMove:8,
            aiMove:4
          },
          fourthMoveScenario2:{
            playerMove:7,
            aiMove:8
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:8
          }
        },
        thirdMoveScenario2:{
          playerMove:2,
          aiMove:1
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:1
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:1
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:1
        }
      },
      secondMoveScenario4:{
        playerMove:9,
        aiMove:6,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:4
        },
        thirdMoveScenario2:{
          playerMove:2,
          aiMove:4
        },
        thirdMoveScenario3:{
          playerMove:8,
          aiMove:4
        },
        thirdMoveScenario4:{
          playerMove:7,
          aiMove:4
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:2,
          fourthMoveScenario1:{
            playerMove:1,
            aiMove:8
          },
          fourthMoveScenario2:{
            playerMove:8,
            aiMove:7
          },
          fourthMoveScenario3:{
            playerMove:7,
            aiMove:8
          }
        }
      },
      secondMoveScenario5:{
        playerMove:8,
        aiMove:4,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:6
        },
        thirdMoveScenario2:{
          playerMove:2,
          aiMove:6
        },
        thirdMoveScenario3:{
          playerMove:6,
          aiMove:9,
          fourthMoveScenario1:{
            playerMove:1,
            aiMove:2
          },
          fourthMoveScenario2:{
            playerMove:2,
            aiMove:1
          },
          fourthMoveScenario3:{
            playerMove:7,
            aiMove:1
          }
        },
        thirdMoveScenario4:{
          playerMove:9,
          aiMove:6
        },
        thirdMoveScenario5:{
          playerMove:7,
          aiMove:6
        }
      },
      secondMoveScenario6:{
        playerMove:7,
        aiMove:2,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:8
        },
        thirdMoveScenario2:{
          playerMove:6,
          aiMove:8
        },
        thirdMoveScenario3:{
          playerMove:9,
          aiMove:8
        },
        thirdMoveScenario4:{
          playerMove:8,
          aiMove:9,
          fourthMoveScenario1:{
            playerMove:1,
            aiMove:4
          },
          fourthMoveScenario2:{
            playerMove:6,
            aiMove:1
          },
          fourthMoveScenario3:{
            playerMove:4,
            aiMove:1
          }
        },
        thirdMoveScenario5:{
          playerMove:4,
          aiMove:8,
        }
      },
      secondMoveScenario7:{
        playerMove:4,
        aiMove:8,
        thirdMoveScenario1:{
          playerMove:1,
          aiMove:2
        },
        thirdMoveScenario2:{
          playerMove:2,
          aiMove:1,
          fourthMoveScenario1:{
            playerMove:6,
            aiMove:9
          },
          fourthMoveScenario2:{
            playerMove:9,
            aiMove:6
          },
          fourthMoveScenario3:{
            playerMove:7,
            aiMove:9
          }
        },
        thirdMoveScenario3:{
          playerMove:6,
          aiMove:2
        },
        thirdMoveScenario4:{
          playerMove:9,
          aiMove:2
        },
        thirdMoveScenario5:{
          playerMove:7,
          aiMove:2
        }
      }
    },
    firstMoveScenario4:{

    },
    firstMoveScenario5:{

    },
    firstMoveScenario6:{

    },
    firstMoveScenario7:{

    },
    firstMoveScenario8:{

    },
    firstMoveScenario9:{

    }
  },

  nextScenario:undefined,

  coordinateToCell: function(coordinate){
    switch (coordinate[0]) {
      case 0:
        switch (coordinate[1]){
          case 0:
            return 1;
          case 1:
            return 4;
          case 2:
            return 7;
        }
      case 1:
        switch (coordinate[1]){
          case 0:
            return 2;
          case 1:
            return 5;
          case 2:
            return 8;
        }
      case 2:
        switch (coordinate[1]){
          case 0:
            return 3;
          case 1:
            return 6;
          case 2:
            return 9;
        }
    }
  },

  cellToCoordinate: function(cell){
    switch (cell){
      case 1:
        return [0,0];
      case 2:
        return [1,0];
      case 3:
        return [2,0];
      case 4:
        return [0,1];
      case 5:
        return [1,1];
      case 6:
        return [2,1];
      case 7:
        return [0,2];
      case 8:
        return [1,2];
      case 9:
        return [2,2];
    }
  },

  aiMove: function(coordinate){
    const playerMove = this.coordinateToCell(coordinate);
    const data = this.nextScenario?this.nextScenario:this.database;
    for(scenario in data){
      const nextData = data[scenario];
      if(nextData.playerMove === playerMove){
        this.nextScenario = nextData;
        return this.cellToCoordinate(nextData.aiMove);
      };
    };
  }
}
